version: "2"
linters:
 default: none
 enable:
 - bidichk
 - errcheck
 - govet
 - ineffassign
 - makezero
 - misspell
 - revive
 - staticcheck
 - unconvert
 - unused
 - whitespace
 settings:
 govet:
  disable:
  - fieldalignment
  enable-all: true
 exclusions:
  generated: lax
 presets:
 - comments
 - std-error-handling
formatters:
 enable:
 - gofmt
 - goimports
 settings:
  gofmt:
   simplify: true
   rewrite-rules:
   - pattern: interface{}
     replacement: any
 exclusions:
  generated: lax
  paths:
  - mock.*
issues:
 max-issues-per-linter: 0 # no maximum
 max-same-issues: 0 # no maximum