version: "2"
linters:
 default: none
 enable:
 - bidichk
 - errcheck
 - govet
 - ineffassign
 - makezero
 - misspell
 - revive
 - staticcheck
 - unconvert
 - unused
 - whitespace
 settings:
 govet:
  disable:
  - fieldalignment
  enable-all: true
 exclusions:
  generated: lax
 presets:
 - error
formatters:
 enable:
 - goimports
 settings:
  gofmt:
   simplify: true
   rewrite-rules:
   - pattern: interface{}
     replacement: any
 exclusions:
  generated: lax
  paths:
  - mock.*
issues:
 max-issues-per-linter: 0 # no maximum
 max-same-issues: 0 # no maximum
 exclude-rules:
 - linters:
   - revive
   text: unused-parameter
 - linters:
   - gofmt
   path: server/matrix/client.go
   line: 83
 - linters:
   - gofmt  
   path: server/matrix_util.go
   line: 151
 - linters:
   - gofmt
   path: server/sync_to_matrix.go
   line: 162